"""ref reference data

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-29 16:22:23.750907
"""
from collections.abc import Sequence

import sqlalchemy as sa
import geoalchemy2
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boundary',
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('area_km2', sa.Float(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_boundary')),
    schema='ref'
    )
    op.create_index('ix_boundary_geom', 'boundary', ['geom'], unique=False, schema='ref', postgresql_using='gist')
    op.create_table('h3_cell',
    sa.Column('h3', sa.String(length=16), nullable=False),
    sa.Column('h3_r8', sa.String(length=16), nullable=False),
    sa.Column('ward_no', sa.Integer(), nullable=True),
    sa.Column('pincode', sa.String(length=6), nullable=True),
    sa.Column('in_gcc', sa.Boolean(), nullable=False),
    sa.Column('area_km2', sa.Float(), nullable=False),
    sa.Column('pop_est', sa.Float(), nullable=False),
    sa.Column('bldg_count', sa.Integer(), nullable=False),
    sa.Column('res_bldg_count', sa.Integer(), nullable=False),
    sa.Column('footfall_pts', sa.Float(), nullable=False),
    sa.Column('comp_convenience', sa.Integer(), nullable=False),
    sa.Column('comp_supermarket', sa.Integer(), nullable=False),
    sa.Column('comp_organised', sa.Integer(), nullable=False),
    sa.Column('retail_count', sa.Integer(), nullable=False),
    sa.Column('road_major_m', sa.Float(), nullable=False),
    sa.Column('road_minor_m', sa.Float(), nullable=False),
    sa.Column('nearest_store_m', sa.Float(), nullable=True),
    sa.Column('nearest_store_code', sa.String(length=20), nullable=True),
    sa.Column('poi_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nbhd', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('opportunity', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('h3', name=op.f('pk_h3_cell')),
    schema='ref'
    )
    op.create_index('ix_h3_cell_geom', 'h3_cell', ['geom'], unique=False, schema='ref', postgresql_using='gist')
    op.create_index('ix_h3_cell_r8', 'h3_cell', ['h3_r8'], unique=False, schema='ref')
    op.create_table('lane_segment',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('osm_id', sa.BigInteger(), nullable=False),
    sa.Column('highway', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('length_m', sa.Float(), nullable=False),
    sa.Column('is_surveyable', sa.Boolean(), nullable=False),
    sa.Column('start_node', sa.BigInteger(), nullable=False),
    sa.Column('end_node', sa.BigInteger(), nullable=False),
    sa.Column('h3_r9', sa.String(length=16), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lane_segment')),
    schema='ref'
    )
    op.create_index('ix_lane_segment_geom', 'lane_segment', ['geom'], unique=False, schema='ref', postgresql_using='gist')
    op.create_index('ix_lane_segment_h3_r9', 'lane_segment', ['h3_r9'], unique=False, schema='ref')
    op.create_table('metric_stats',
    sa.Column('metric', sa.String(length=40), nullable=False),
    sa.Column('breakpoints', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('metric', name=op.f('pk_metric_stats')),
    schema='ref'
    )
    op.create_table('osm_building',
    sa.Column('osm_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('use_class', sa.String(length=12), nullable=False),
    sa.Column('levels', sa.SmallInteger(), nullable=False),
    sa.Column('res_weight', sa.Float(), nullable=False),
    sa.Column('pop_est', sa.Float(), nullable=True),
    sa.Column('h3_r9', sa.String(length=16), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('osm_id', name=op.f('pk_osm_building')),
    schema='ref'
    )
    op.create_index('ix_osm_building_geom', 'osm_building', ['geom'], unique=False, schema='ref', postgresql_using='gist')
    op.create_index('ix_osm_building_h3_r9', 'osm_building', ['h3_r9'], unique=False, schema='ref')
    op.create_table('osm_poi',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('osm_type', sa.String(length=1), nullable=False),
    sa.Column('osm_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('subcategory', sa.String(length=40), nullable=False),
    sa.Column('footfall_weight', sa.Float(), nullable=False),
    sa.Column('competitor_tier', sa.SmallInteger(), nullable=False),
    sa.Column('h3_r9', sa.String(length=16), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_osm_poi')),
    schema='ref'
    )
    op.create_index('ix_osm_poi_category', 'osm_poi', ['category'], unique=False, schema='ref')
    op.create_index('ix_osm_poi_geom', 'osm_poi', ['geom'], unique=False, schema='ref', postgresql_using='gist')
    op.create_index('ix_osm_poi_h3_r9', 'osm_poi', ['h3_r9'], unique=False, schema='ref')
    op.create_table('pincode',
    sa.Column('pincode', sa.String(length=6), nullable=False),
    sa.Column('office_name', sa.String(length=120), nullable=False),
    sa.Column('division', sa.String(length=80), nullable=True),
    sa.Column('area_km2', sa.Float(), nullable=False),
    sa.Column('in_cma_share', sa.Float(), nullable=False),
    sa.Column('pop_est', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('pincode', name=op.f('pk_pincode')),
    schema='ref'
    )
    op.create_index('ix_pincode_geom', 'pincode', ['geom'], unique=False, schema='ref', postgresql_using='gist')
    op.create_table('rent_band_mock',
    sa.Column('pincode', sa.String(length=6), nullable=False),
    sa.Column('tier', sa.String(length=12), nullable=False),
    sa.Column('rent_psf_min', sa.Float(), nullable=False),
    sa.Column('rent_psf_max', sa.Float(), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('pincode', name=op.f('pk_rent_band_mock')),
    schema='ref'
    )
    op.create_table('savomart_store',
    sa.Column('store_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('zone', sa.String(length=8), nullable=False),
    sa.Column('address_pincode', sa.String(length=6), nullable=True),
    sa.Column('geo_pincode', sa.String(length=6), nullable=True),
    sa.Column('is_operational', sa.Boolean(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('store_code', name=op.f('pk_savomart_store')),
    schema='ref'
    )
    op.create_index('ix_savomart_store_geom', 'savomart_store', ['geom'], unique=False, schema='ref', postgresql_using='gist')
    op.create_table('ward',
    sa.Column('ward_no', sa.Integer(), nullable=False),
    sa.Column('zone_no', sa.String(length=8), nullable=False),
    sa.Column('zone_name', sa.String(length=60), nullable=False),
    sa.Column('is_old_city', sa.Boolean(), nullable=False),
    sa.Column('area_km2', sa.Float(), nullable=False),
    sa.Column('pop_est', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('ward_no', name=op.f('pk_ward')),
    schema='ref'
    )
    op.create_index('ix_ward_geom', 'ward', ['geom'], unique=False, schema='ref', postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ward_geom', table_name='ward', schema='ref', postgresql_using='gist')
    op.drop_table('ward', schema='ref')
    op.drop_index('ix_savomart_store_geom', table_name='savomart_store', schema='ref', postgresql_using='gist')
    op.drop_table('savomart_store', schema='ref')
    op.drop_table('rent_band_mock', schema='ref')
    op.drop_index('ix_pincode_geom', table_name='pincode', schema='ref', postgresql_using='gist')
    op.drop_table('pincode', schema='ref')
    op.drop_index('ix_osm_poi_h3_r9', table_name='osm_poi', schema='ref')
    op.drop_index('ix_osm_poi_geom', table_name='osm_poi', schema='ref', postgresql_using='gist')
    op.drop_index('ix_osm_poi_category', table_name='osm_poi', schema='ref')
    op.drop_table('osm_poi', schema='ref')
    op.drop_index('ix_osm_building_h3_r9', table_name='osm_building', schema='ref')
    op.drop_index('ix_osm_building_geom', table_name='osm_building', schema='ref', postgresql_using='gist')
    op.drop_table('osm_building', schema='ref')
    op.drop_table('metric_stats', schema='ref')
    op.drop_index('ix_lane_segment_h3_r9', table_name='lane_segment', schema='ref')
    op.drop_index('ix_lane_segment_geom', table_name='lane_segment', schema='ref', postgresql_using='gist')
    op.drop_table('lane_segment', schema='ref')
    op.drop_index('ix_h3_cell_r8', table_name='h3_cell', schema='ref')
    op.drop_index('ix_h3_cell_geom', table_name='h3_cell', schema='ref', postgresql_using='gist')
    op.drop_table('h3_cell', schema='ref')
    op.drop_index('ix_boundary_geom', table_name='boundary', schema='ref', postgresql_using='gist')
    op.drop_table('boundary', schema='ref')
    # ### end Alembic commands ###
