"""areas and reports

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-29 16:35:02.890092
"""
from collections.abc import Sequence

import sqlalchemy as sa
import geoalchemy2
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geocode_cache',
    sa.Column('query', sa.String(length=200), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('query', name=op.f('pk_geocode_cache')),
    schema='app'
    )
    op.create_table('area',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('selection_type', sa.String(length=12), nullable=False),
    sa.Column('selection_input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('h3_cells', postgresql.ARRAY(sa.String(length=16)), nullable=False),
    sa.Column('area_km2', sa.Float(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['app.user.id'], name=op.f('fk_area_created_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_area')),
    schema='app'
    )
    op.create_index('ix_area_geom', 'area', ['geom'], unique=False, schema='app', postgresql_using='gist')
    op.create_table('area_report',
    sa.Column('area_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('scoring_version', sa.String(length=10), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=2), nullable=True),
    sa.Column('confidence', sa.String(length=8), nullable=True),
    sa.Column('confidence_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sub_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hotspots', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('facts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('narrative', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('narrative_source', sa.String(length=10), nullable=True),
    sa.Column('llm_model', sa.String(length=80), nullable=True),
    sa.Column('data_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['app.area.id'], name=op.f('fk_area_report_area_id_area'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['app.user.id'], name=op.f('fk_area_report_created_by_user')),
    sa.ForeignKeyConstraint(['job_id'], ['app.job.id'], name=op.f('fk_area_report_job_id_job'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_area_report')),
    schema='app'
    )
    op.create_index('ix_area_report_area', 'area_report', ['area_id'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_area_report_area', table_name='area_report', schema='app')
    op.drop_table('area_report', schema='app')
    op.drop_index('ix_area_geom', table_name='area', schema='app', postgresql_using='gist')
    op.drop_table('area', schema='app')
    op.drop_table('geocode_cache', schema='app')
    # ### end Alembic commands ###
