"""m2 properties and pipeline

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-29 20:39:52.244439
"""
from collections.abc import Sequence

import sqlalchemy as sa
import geoalchemy2
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Human-friendly property codes: SS-CHN-0001, SS-CHN-0002, ...
    op.execute("CREATE SEQUENCE IF NOT EXISTS app.property_code_seq")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scouting_task',
    sa.Column('report_id', sa.UUID(), nullable=True),
    sa.Column('area_id', sa.UUID(), nullable=True),
    sa.Column('hotspot_id', sa.String(length=8), nullable=True),
    sa.Column('h3', sa.String(length=16), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('radius_m', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('assignee_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['app.area.id'], name=op.f('fk_scouting_task_area_id_area'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_by'], ['app.user.id'], name=op.f('fk_scouting_task_assigned_by_user')),
    sa.ForeignKeyConstraint(['assignee_id'], ['app.user.id'], name=op.f('fk_scouting_task_assignee_id_user')),
    sa.ForeignKeyConstraint(['report_id'], ['app.area_report.id'], name=op.f('fk_scouting_task_report_id_area_report'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scouting_task')),
    schema='app'
    )
    op.create_index('ix_scouting_task_assignee', 'scouting_task', ['assignee_id', 'status'], unique=False, schema='app')
    op.create_table('property',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('stage_before_hold', sa.String(length=20), nullable=True),
    sa.Column('scouting_task_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('pin', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('gps_fix', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=True), nullable=True),
    sa.Column('gps_accuracy_m', sa.Float(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('landmark', sa.String(length=160), nullable=True),
    sa.Column('pincode', sa.String(length=6), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rent_monthly', sa.Float(), nullable=True),
    sa.Column('carpet_sqft', sa.Float(), nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duplicate_of', sa.UUID(), nullable=True),
    sa.Column('latest_score', sa.Float(), nullable=True),
    sa.Column('latest_recommendation', sa.String(length=10), nullable=True),
    sa.Column('latest_evaluation_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['app.user.id'], name=op.f('fk_property_created_by_user')),
    sa.ForeignKeyConstraint(['duplicate_of'], ['app.property.id'], name=op.f('fk_property_duplicate_of_property'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scouting_task_id'], ['app.scouting_task.id'], name=op.f('fk_property_scouting_task_id_scouting_task'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property')),
    sa.UniqueConstraint('code', name=op.f('uq_property_code')),
    schema='app'
    )
    op.create_index('ix_property_created_by', 'property', ['created_by'], unique=False, schema='app')
    op.create_index('ix_property_pin', 'property', ['pin'], unique=False, schema='app', postgresql_using='gist')
    op.create_index('ix_property_stage', 'property', ['stage'], unique=False, schema='app')
    op.create_table('pipeline_event',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('from_stage', sa.String(length=20), nullable=True),
    sa.Column('to_stage', sa.String(length=20), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['app.user.id'], name=op.f('fk_pipeline_event_actor_id_user')),
    sa.ForeignKeyConstraint(['property_id'], ['app.property.id'], name=op.f('fk_pipeline_event_property_id_property'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_event')),
    schema='app'
    )
    op.create_index('ix_pipeline_event_property', 'pipeline_event', ['property_id', 'at'], unique=False, schema='app')
    op.create_table('property_evaluation',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('location_score', sa.Float(), nullable=True),
    sa.Column('site_score', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.String(length=10), nullable=True),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('inputs_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('facts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('narrative', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('narrative_source', sa.String(length=10), nullable=True),
    sa.Column('llm_model', sa.String(length=80), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['app.job.id'], name=op.f('fk_property_evaluation_job_id_job'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['app.property.id'], name=op.f('fk_property_evaluation_property_id_property'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_evaluation')),
    schema='app'
    )
    op.create_index('ix_property_evaluation_property', 'property_evaluation', ['property_id', 'version'], unique=False, schema='app')
    op.create_table('property_photo',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('path', sa.String(length=300), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['app.property.id'], name=op.f('fk_property_photo_property_id_property'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['app.user.id'], name=op.f('fk_property_photo_uploaded_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_photo')),
    schema='app'
    )
    op.create_index('ix_property_photo_property', 'property_photo', ['property_id'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP SEQUENCE IF EXISTS app.property_code_seq")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_property_photo_property', table_name='property_photo', schema='app')
    op.drop_table('property_photo', schema='app')
    op.drop_index('ix_property_evaluation_property', table_name='property_evaluation', schema='app')
    op.drop_table('property_evaluation', schema='app')
    op.drop_index('ix_pipeline_event_property', table_name='pipeline_event', schema='app')
    op.drop_table('pipeline_event', schema='app')
    op.drop_index('ix_property_stage', table_name='property', schema='app')
    op.drop_index('ix_property_pin', table_name='property', schema='app', postgresql_using='gist')
    op.drop_index('ix_property_created_by', table_name='property', schema='app')
    op.drop_table('property', schema='app')
    op.drop_index('ix_scouting_task_assignee', table_name='scouting_task', schema='app')
    op.drop_table('scouting_task', schema='app')
    # ### end Alembic commands ###
