"""m3 catchment studies

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-29 21:27:47.081268
"""
from collections.abc import Sequence

import sqlalchemy as sa
import geoalchemy2
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE SEQUENCE IF NOT EXISTS app.study_code_seq")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catchment_study',
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('target_type', sa.String(length=10), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('report_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('radius_m', sa.Integer(), nullable=False),
    sa.Column('reuse_mode', sa.String(length=8), nullable=False),
    sa.Column('reuse_coverage', sa.Float(), nullable=False),
    sa.Column('reused_study_ids', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('total_length_m', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('planned_by', sa.UUID(), nullable=True),
    sa.Column('insight', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('insight_narrative', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['app.job.id'], name=op.f('fk_catchment_study_job_id_job'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['planned_by'], ['app.user.id'], name=op.f('fk_catchment_study_planned_by_user')),
    sa.ForeignKeyConstraint(['property_id'], ['app.property.id'], name=op.f('fk_catchment_study_property_id_property'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['app.area_report.id'], name=op.f('fk_catchment_study_report_id_area_report'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['app.user.id'], name=op.f('fk_catchment_study_requested_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catchment_study')),
    sa.UniqueConstraint('code', name=op.f('uq_catchment_study_code')),
    schema='app'
    )
    op.create_index('ix_catchment_study_geom', 'catchment_study', ['geom'], unique=False, schema='app', postgresql_using='gist')
    op.create_index('ix_catchment_study_status', 'catchment_study', ['status'], unique=False, schema='app')
    op.create_table('work_chunk',
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=4), nullable=False),
    sa.Column('effort_m', sa.Float(), nullable=False),
    sa.Column('lane_count', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['app.user.id'], name=op.f('fk_work_chunk_assignee_id_user')),
    sa.ForeignKeyConstraint(['study_id'], ['app.catchment_study.id'], name=op.f('fk_work_chunk_study_id_catchment_study'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_chunk')),
    schema='app'
    )
    op.create_index('ix_work_chunk_assignee', 'work_chunk', ['assignee_id'], unique=False, schema='app')
    op.create_index('ix_work_chunk_study', 'work_chunk', ['study_id'], unique=False, schema='app')
    op.create_table('lane_survey',
    sa.Column('client_uuid', sa.UUID(), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('lane_id', sa.String(length=40), nullable=False),
    sa.Column('surveyor_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_seed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['app.work_chunk.id'], name=op.f('fk_lane_survey_chunk_id_work_chunk'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lane_id'], ['ref.lane_segment.id'], name=op.f('fk_lane_survey_lane_id_lane_segment')),
    sa.ForeignKeyConstraint(['study_id'], ['app.catchment_study.id'], name=op.f('fk_lane_survey_study_id_catchment_study'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['surveyor_id'], ['app.user.id'], name=op.f('fk_lane_survey_surveyor_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lane_survey')),
    sa.UniqueConstraint('client_uuid', name='uq_lane_survey_client_uuid'),
    schema='app'
    )
    op.create_index('ix_lane_survey_lane', 'lane_survey', ['lane_id', 'status'], unique=False, schema='app')
    op.create_index('ix_lane_survey_study', 'lane_survey', ['study_id'], unique=False, schema='app')
    op.create_table('study_lane',
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('lane_id', sa.String(length=40), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('reused_survey_id', sa.UUID(), nullable=True),
    sa.Column('length_m', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['app.work_chunk.id'], name=op.f('fk_study_lane_chunk_id_work_chunk'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lane_id'], ['ref.lane_segment.id'], name=op.f('fk_study_lane_lane_id_lane_segment')),
    sa.ForeignKeyConstraint(['study_id'], ['app.catchment_study.id'], name=op.f('fk_study_lane_study_id_catchment_study'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_id', 'lane_id', name=op.f('pk_study_lane')),
    schema='app'
    )
    op.create_index('ix_study_lane_chunk', 'study_lane', ['chunk_id'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP SEQUENCE IF EXISTS app.study_code_seq")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_study_lane_chunk', table_name='study_lane', schema='app')
    op.drop_table('study_lane', schema='app')
    op.drop_index('ix_lane_survey_study', table_name='lane_survey', schema='app')
    op.drop_index('ix_lane_survey_lane', table_name='lane_survey', schema='app')
    op.drop_table('lane_survey', schema='app')
    op.drop_index('ix_work_chunk_study', table_name='work_chunk', schema='app')
    op.drop_index('ix_work_chunk_assignee', table_name='work_chunk', schema='app')
    op.drop_table('work_chunk', schema='app')
    op.drop_index('ix_catchment_study_status', table_name='catchment_study', schema='app')
    op.drop_index('ix_catchment_study_geom', table_name='catchment_study', schema='app', postgresql_using='gist')
    op.drop_table('catchment_study', schema='app')
    # ### end Alembic commands ###
